### ISSUE TITLE
smallish jpeg doesn't work

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#1]
i tried dragging a png (cut out, transparent background) or a jpeg (smaller in size) but neither seem to work.

i tried these:
https://github.com/cmuartfab/dranimate/blob/master/bin/data/images/Shahnameh/Killing%20Ashkeboos_1024.png

https://github.com/cmuartfab/dranimate/blob/master/bin/data/images/Shahnameh/Killing%20Ashkeboos-black_1024.jpg

suggestions?

**Comment by devbego** [comment]
i added support for when images have an alpha channel.

all should be well now!
