### ISSUE TITLE
leap calibration difficulties

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#10]
the leap calibration seems broken/hard to use:
i click on 'c' (updated the repo, please pull/sync before updating) to calibrate,  i see the points, but the position on the screen seems off; when my hand is directly over the leap, the points/fingers are top right of screen.

-after i calibrate, when i try to map to a puppet, it seems that the system is using absolute finger positions not relative ones because the attached puppet verticies jump to the center of the screen
-palm position doesn't appear to control the overall position of the whole puppet

**Comment by devbego** [comment]
The palm now controls the root vertex and the fingers new get calibrated correctly!
