### ISSUE TITLE
can't compile latest version

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#2]
i get this error:
![image](https://cloud.githubusercontent.com/assets/518356/7785559/b74f6782-0163-11e5-90cf-9357909cbf9e.png)

/Users/ali/GoogleDrive/Development/of_v0.8.4_osx_release/apps/myApps/dranimate/src/ofApp.cpp:334:15: No member named 'controlPointsVector' in 'ofxPuppetInteractive'

**Comment by devbego** [comment]
this was caused when I added an extra variable to ofxPuppet ... without my version of the addon, dranimate wouldn't compile.

fixed now!
