### ISSUE TITLE
can not compile, missing "ContinuousHiddenMarkovModel.cpp"

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#22]
clang: error: no such file or directory: '/Users/ali/Documents/Development/of_v0.8.4_osx_release/addons/ofxLeapGestures/libs/ClassificationModules/HMM/ContinuousHiddenMarkovModel.cpp'
clang: warning: -lpthread: 'linker' input unused

**Comment by devbego** [comment]
the latest version requires ofxLeapGestures:

https://github.com/cmuartfab/ofxLeapGestures

I'll add it to the readme !
