### ISSUE TITLE
ofxOsc

### ISSUE THREAD

**Issue by ge53** [cmuartfab/dranimate#23]
-I am trying to compile "dranimate" but getting a consistent error (OSX 10.10, XCode 6.4)--"(null): No such file or directory: '../../../addons/ofxOsc/libs/oscpack/lib/osx/libOsc.a'"--it looks like a zipped executable when downloaded/can't "unarchive" on Mac, can't run in terminal (same error: "-bash: ./Users/Downloads/dranimate-master/dranimate-master/oscpack-lib/lib/osx/libOsc.a: No such file or directory")--I'm not C++ savvy but...Can you help?Thanks!

​Geraldine

**Comment by zrispo** [comment]
Similar issue to <a href="https://github.com/cmuartfab/dranimate/issues/24">this</a>, looks like it was an issue with the xcode project build settings. It should be fixed with the latest commit!

**Comment by ge53** [comment]
Thanks to you both for the quick response! gonna try again :)

http://myvernacular.geraldineerman.com

**Comment by ge53** [comment]
thansk for the quick response!
