### ISSUE TITLE
can't compile: ofxSyphon issues

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#24]
with the latest on github now, i can't compile the project:

![image](https://cloud.githubusercontent.com/assets/518356/8782300/6f94ab1c-2ee2-11e5-82ce-377d8bb96830.png)

**Comment by zrispo** [comment]
Looks like it was another build settings issue (accidentally used an absolute path instead of a relative path). I fixed it in the latest commit:

https://github.com/cmuartfab/dranimate/commit/1485b88cb4d9263971a3772d36ac480863ff58d9
