### ISSUE TITLE
syphon not working?

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#25]
hello,
i got the project compiled, i'm testing with millumin, i'm not able to see any syphon sources, after i've made a recording in a puppet layer:

![image](https://cloud.githubusercontent.com/assets/518356/8782903/8028b35c-2ee6-11e5-90b1-e39656bec9d6.png)

**Comment by zrispo** [comment]
Whoops, my mistake, I forgot to change the settings back to normal when I pushed the latest commit.

The "syphonServersEnabled" value in settings/launch.xml has to be set to 1. It's currently set to 0. Here's what launch.xml should look like:

![screen shot 2015-07-20 at 1 58 32 pm](https://cloud.githubusercontent.com/assets/4970417/8783056/6f5b6cda-2ee7-11e5-84e1-916e4aa77e18.png)

**Comment by batchku** [comment]
ok, i fixed that.
however i'm now finding that the leap-rigging is not working.
i point with my left hand and wiggle a right hand finger...
nothing happens.  thoughts?

a

**Comment by batchku** [comment]
great.
good to know of the setting files.
