### ISSUE TITLE
leap-based rigging is not working

### ISSUE THREAD

**Issue by batchku** [cmuartfab/dranimate#26]
first i calibrate the leap,
then while editing a puppet,
i point with my left index finger, and i wiggle the desired finger on the right hand.
no line is drawn and no e-spot is added.

something different here?

![screenshot 2015-07-20 14 17 44](https://cloud.githubusercontent.com/assets/518356/8783538/8aa13788-2eea-11e5-99f0-99192ab7f626.png)

**Comment by batchku** [comment]
os there something i am missing?

**Comment by zrispo** [comment]
Huh, not sure about this, it seems to be working fine for me.

Does it work sometimes, or not at all? It might be that the controls are just not sensitive enough and you have to wiggle harder.

Also, we'll have to get more people to test the leap rigging system soon!! It's still pretty confusing to use.

**Comment by batchku** [comment]
We should expose the leap finger wiggle sensitivity parameter as a gui
element in the leap calibration page.

**Comment by zrispo** [comment]
added leap sensitivity to the xml launch settings !!
